# Generated by Django 3.1.2 on 2020-10-24 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(auto_created=True, verbose_name='Data urodzenia')),
                ('name', models.CharField(blank=None, max_length=255, null=None, verbose_name='Imię')),
                ('last_name', models.CharField(blank=None, max_length=255, null=None, verbose_name='Nazwisko')),
                ('club', models.CharField(default=True, max_length=255, verbose_name='Klub')),
                ('position', models.CharField(choices=[('GK', 'goalkeeper'), ('RB', 'right back'), ('CB', 'centre back'), ('LB', 'left back'), ('CM', 'central midfileder'), ('LM', 'left midfileder'), ('RM', 'right midfileder'), ('RW', 'right winger'), ('LW', 'left winger'), ('FW', 'forward'), ('CAM', 'central attacking midfielder'), ('CDM', 'central defending midfielder')], max_length=3, verbose_name='Pozycja')),
                ('rating', models.FloatField(default=False, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10.0)])),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Zawodnik',
                'verbose_name_plural': 'Zawodnicy',
            },
        ),
    ]
